name: at_lookup
description: A Dart library that contains the core commands that can be used with a secondary server (scan, update, lookup, llookup, plookup, etc.)
version: 3.0.25
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  crypton: ^2.0.1
  crypto: ^3.0.1
  at_utils: ^3.0.10
  at_commons: ^3.0.17
  mutex: ^3.0.0
  mocktail: ^0.3.0

#dependency_overrides:
#  at_commons:
#      git:
#        url: https://github.com/atsign-foundation/at_tools.git
#        path: at_commons
#        ref: exception_handling_changes

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.1
