name: at_lookup
description: Library for executing at commands on a secondary server. Example - scan. update, lookup, llookup, plookup etc.
version: 1.0.0+8
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  crypton: ^2.0.1
  crypto: ^3.0.0
  at_commons: ^1.0.1+8
  at_utils: ^1.0.1+8

#dependency_overrides:
#  at_utils:
#    path: ../../at_tools/at_utils
#  at_commons:
#    path: ../../at_tools/at_commons
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
