name: at_lookup
description: Library for executing at commands on a secondary server. Example - scan. update, lookup, llookup, plookup etc.
version: 1.0.0+7
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  crypton: ^1.1.0
  crypto: ^2.1.5
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: dev_env
      version: ^1.0.1+7

#dependency_overrides:
#  at_utils:
#    path: ../../at_tools/at_utils
#  at_commons:
#    path: ../../at_tools/at_commons
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
