name: at_lookup
description: A Dart library that contains the core commands that can be used with a secondary server (scan, update, lookup, llookup, plookup, etc.)
version: 3.0.33
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.com
documentation: https://docs.atsign.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  crypton: ^2.0.1
  crypto: ^3.0.1
  at_utils: ^3.0.11
  at_commons: ^3.0.26
  mutex: ^3.0.0
  mocktail: ^0.3.0
  meta: ^1.8.0

dependency_overrides:
  at_chops:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_chops
      ref: at_chops
#    path: ../at_chops

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.1
