name: at_onboarding_cli
description: Dart tool to authenticate, onboard and perform complex operations on @sign from command-line-interface.
version: 1.1.0
repository: https://github.com/atsign-foundation/at_libraries/tree/trunk/at_onboarding_cli

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
   at_utils: ^3.0.4
   at_client: ^3.0.31
   at_lookup: ^3.0.28
   zxing2: ^0.1.0
   image: ^3.1.1
   crypton: ^2.0.3
   at_commons: ^3.0.21
   encrypt: ^5.0.1
   at_server_status: ^1.0.3
   path: ^1.8.1

#dependency_overrides:
#  at_lookup:
#    git:
#      url: https://github.com/atsign-foundation/at_libraries.git
#      path: at_lookup
#      ref: trunk
#
#  at_client:
#    git:
#      url: https://github.com/atsign-foundation/at_client_sdk.git
#      path: at_client
#      ref: trunk
#
#  at_commons:
#    git:
#      url: https://github.com/atsign-foundation/at_tools.git
#      path: at_commons
#      ref: trunk


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  at_demo_data: ^0.0.3+1
