name: at_chops
description: Package for at_protocol cryptographic and hashing operations
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  encrypt: ^5.0.1
  crypton: ^2.1.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
