name: at_onboarding_cli
description: Dart tool to authenticate, onboard and perform complex operations on atSign seccondaries from command-line-interface.
version: 1.2.6
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.com
documentation: https://docs.atsign.com/

environment:
  sdk: '>=2.15.1 <4.0.0'

executables:
  at_register: register_cli
  at_activate: activate_cli

dependencies:
  at_commons: ^3.0.44
  at_utils: ^3.0.12
  at_chops: ^1.0.3
  at_lookup: ^3.0.36
  at_client: ^3.0.58
  at_server_status: ^1.0.3
  zxing2: ^0.1.0
  image: ^3.1.1
  crypton: ^2.0.3
  encrypt: ^5.0.1
  path: ^1.8.1
  args: ^2.3.1
  http: ^0.13.5

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: packages/at_commons
      ref: dart-3
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: packages/at_utils
      ref: dart-3
  at_chops:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_chops
      ref: dart-3
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: dart-3
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: dart-3
  at_server_status:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_server_status
      ref: dart-3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  at_demo_data: ^1.0.0
  mocktail: ^0.3.0
