name: at_onboarding_cli
description: Dart tool to authenticate, onboard and perform complex operations on atSign seccondaries from command-line-interface.
version: 1.2.5
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.com
documentation: https://docs.atsign.com/

environment:
  sdk: '>=2.15.1 <3.0.0'

executables:
  at_register: register_cli
  at_activate: activate_cli

dependencies:
   at_utils: ^3.0.12
   at_client: ^3.0.56
   at_lookup: ^3.0.35
   zxing2: ^0.1.0
   image: ^3.1.1
   crypton: ^2.0.3
   at_commons: ^3.0.33
   encrypt: ^5.0.1
   at_server_status: ^1.0.3
   path: ^1.8.1
   args: ^2.3.1
   http: ^0.13.5
   at_chops: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  at_demo_data: ^1.0.0
  mocktail: ^0.3.0
