name: at_server_status
description: The at_server_status library provides an easy means to check on the status of the @root server as well as the @server for a particular @sign.
documentation: https://atsign.dev/apidocs
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev
publish_to: none

version: 0.1.0+2

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: dev_env
      version: ^1.0.0+7
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
