name: at_server_status
description: The at_server_status library provides an easy means to check on the status of the @root server as well as the @server for a particular @sign.
documentation: https://atsign.dev/apidocs
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev
publish_to: none
version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_lookup: ^1.0.0+8
  at_utils: ^1.0.1+8
  at_commons: ^1.0.1+8

dependency_overrides:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: trunk
      version: ^2.0.1
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: trunk
      version: ^2.0.1
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: trunk
      version: ^2.0.1
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
