name: at_server_status
description: A Dart library that provides a means to check on the status of the @‎root server as well as the secondary server for any particular @‎sign.
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.com
documentation: https://docs.atsign.com/
version: 1.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_lookup: ^3.0.2
  at_utils: ^3.0.0
  at_commons: ^3.0.0
  uuid: ^3.0.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.1
