name: at_lookup_example
description: An example application to demostrate the at_lookup package usage.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  at_utils: ^3.0.2
  at_commons: ^3.0.2
  at_lookup: ^3.0.5

dev_dependencies:
  lints: ^1.0.0
